/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FarmsRouteImport } from './routes/farms'
import { Route as FarmersRouteImport } from './routes/farmers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YieldNewRouteImport } from './routes/yield.new'
import { Route as SoilTestsNewRouteImport } from './routes/soil-tests.new'
import { Route as FertilizerNewRouteImport } from './routes/fertilizer.new'
import { Route as FarmsNewRouteImport } from './routes/farms.new'
import { Route as FarmersNewRouteImport } from './routes/farmers.new'
import { Route as CropCyclesNewRouteImport } from './routes/crop-cycles.new'
import { Route as FarmersFarmer_idEditRouteImport } from './routes/farmers.$farmer_id.edit'

const FarmsRoute = FarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersRoute = FarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YieldNewRoute = YieldNewRouteImport.update({
  id: '/yield/new',
  path: '/yield/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilTestsNewRoute = SoilTestsNewRouteImport.update({
  id: '/soil-tests/new',
  path: '/soil-tests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FertilizerNewRoute = FertilizerNewRouteImport.update({
  id: '/fertilizer/new',
  path: '/fertilizer/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsNewRoute = FarmsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FarmsRoute,
} as any)
const FarmersNewRoute = FarmersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FarmersRoute,
} as any)
const CropCyclesNewRoute = CropCyclesNewRouteImport.update({
  id: '/crop-cycles/new',
  path: '/crop-cycles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersFarmer_idEditRoute = FarmersFarmer_idEditRouteImport.update({
  id: '/$farmer_id/edit',
  path: '/$farmer_id/edit',
  getParentRoute: () => FarmersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/farmers': typeof FarmersRouteWithChildren
  '/farms': typeof FarmsRouteWithChildren
  '/crop-cycles/new': typeof CropCyclesNewRoute
  '/farmers/new': typeof FarmersNewRoute
  '/farms/new': typeof FarmsNewRoute
  '/fertilizer/new': typeof FertilizerNewRoute
  '/soil-tests/new': typeof SoilTestsNewRoute
  '/yield/new': typeof YieldNewRoute
  '/farmers/$farmer_id/edit': typeof FarmersFarmer_idEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/farmers': typeof FarmersRouteWithChildren
  '/farms': typeof FarmsRouteWithChildren
  '/crop-cycles/new': typeof CropCyclesNewRoute
  '/farmers/new': typeof FarmersNewRoute
  '/farms/new': typeof FarmsNewRoute
  '/fertilizer/new': typeof FertilizerNewRoute
  '/soil-tests/new': typeof SoilTestsNewRoute
  '/yield/new': typeof YieldNewRoute
  '/farmers/$farmer_id/edit': typeof FarmersFarmer_idEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/farmers': typeof FarmersRouteWithChildren
  '/farms': typeof FarmsRouteWithChildren
  '/crop-cycles/new': typeof CropCyclesNewRoute
  '/farmers/new': typeof FarmersNewRoute
  '/farms/new': typeof FarmsNewRoute
  '/fertilizer/new': typeof FertilizerNewRoute
  '/soil-tests/new': typeof SoilTestsNewRoute
  '/yield/new': typeof YieldNewRoute
  '/farmers/$farmer_id/edit': typeof FarmersFarmer_idEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/farmers'
    | '/farms'
    | '/crop-cycles/new'
    | '/farmers/new'
    | '/farms/new'
    | '/fertilizer/new'
    | '/soil-tests/new'
    | '/yield/new'
    | '/farmers/$farmer_id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/farmers'
    | '/farms'
    | '/crop-cycles/new'
    | '/farmers/new'
    | '/farms/new'
    | '/fertilizer/new'
    | '/soil-tests/new'
    | '/yield/new'
    | '/farmers/$farmer_id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/farmers'
    | '/farms'
    | '/crop-cycles/new'
    | '/farmers/new'
    | '/farms/new'
    | '/fertilizer/new'
    | '/soil-tests/new'
    | '/yield/new'
    | '/farmers/$farmer_id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FarmersRoute: typeof FarmersRouteWithChildren
  FarmsRoute: typeof FarmsRouteWithChildren
  CropCyclesNewRoute: typeof CropCyclesNewRoute
  FertilizerNewRoute: typeof FertilizerNewRoute
  SoilTestsNewRoute: typeof SoilTestsNewRoute
  YieldNewRoute: typeof YieldNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/farms': {
      id: '/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof FarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers': {
      id: '/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof FarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yield/new': {
      id: '/yield/new'
      path: '/yield/new'
      fullPath: '/yield/new'
      preLoaderRoute: typeof YieldNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil-tests/new': {
      id: '/soil-tests/new'
      path: '/soil-tests/new'
      fullPath: '/soil-tests/new'
      preLoaderRoute: typeof SoilTestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertilizer/new': {
      id: '/fertilizer/new'
      path: '/fertilizer/new'
      fullPath: '/fertilizer/new'
      preLoaderRoute: typeof FertilizerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/new': {
      id: '/farms/new'
      path: '/new'
      fullPath: '/farms/new'
      preLoaderRoute: typeof FarmsNewRouteImport
      parentRoute: typeof FarmsRoute
    }
    '/farmers/new': {
      id: '/farmers/new'
      path: '/new'
      fullPath: '/farmers/new'
      preLoaderRoute: typeof FarmersNewRouteImport
      parentRoute: typeof FarmersRoute
    }
    '/crop-cycles/new': {
      id: '/crop-cycles/new'
      path: '/crop-cycles/new'
      fullPath: '/crop-cycles/new'
      preLoaderRoute: typeof CropCyclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/$farmer_id/edit': {
      id: '/farmers/$farmer_id/edit'
      path: '/$farmer_id/edit'
      fullPath: '/farmers/$farmer_id/edit'
      preLoaderRoute: typeof FarmersFarmer_idEditRouteImport
      parentRoute: typeof FarmersRoute
    }
  }
}

interface FarmersRouteChildren {
  FarmersNewRoute: typeof FarmersNewRoute
  FarmersFarmer_idEditRoute: typeof FarmersFarmer_idEditRoute
}

const FarmersRouteChildren: FarmersRouteChildren = {
  FarmersNewRoute: FarmersNewRoute,
  FarmersFarmer_idEditRoute: FarmersFarmer_idEditRoute,
}

const FarmersRouteWithChildren =
  FarmersRoute._addFileChildren(FarmersRouteChildren)

interface FarmsRouteChildren {
  FarmsNewRoute: typeof FarmsNewRoute
}

const FarmsRouteChildren: FarmsRouteChildren = {
  FarmsNewRoute: FarmsNewRoute,
}

const FarmsRouteWithChildren = FarmsRoute._addFileChildren(FarmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FarmersRoute: FarmersRouteWithChildren,
  FarmsRoute: FarmsRouteWithChildren,
  CropCyclesNewRoute: CropCyclesNewRoute,
  FertilizerNewRoute: FertilizerNewRoute,
  SoilTestsNewRoute: SoilTestsNewRoute,
  YieldNewRoute: YieldNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
