/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YieldNewRouteImport } from './routes/yield.new'
import { Route as SoilTestsNewRouteImport } from './routes/soil-tests.new'
import { Route as FertilizerNewRouteImport } from './routes/fertilizer.new'
import { Route as FarmsNewRouteImport } from './routes/farms.new'
import { Route as FarmersNewRouteImport } from './routes/farmers.new'
import { Route as CropCyclesNewRouteImport } from './routes/crop-cycles.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YieldNewRoute = YieldNewRouteImport.update({
  id: '/yield/new',
  path: '/yield/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilTestsNewRoute = SoilTestsNewRouteImport.update({
  id: '/soil-tests/new',
  path: '/soil-tests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FertilizerNewRoute = FertilizerNewRouteImport.update({
  id: '/fertilizer/new',
  path: '/fertilizer/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsNewRoute = FarmsNewRouteImport.update({
  id: '/farms/new',
  path: '/farms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersNewRoute = FarmersNewRouteImport.update({
  id: '/farmers/new',
  path: '/farmers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CropCyclesNewRoute = CropCyclesNewRouteImport.update({
  id: '/crop-cycles/new',
  path: '/crop-cycles/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crop-cycles/new': typeof CropCyclesNewRoute
  '/farmers/new': typeof FarmersNewRoute
  '/farms/new': typeof FarmsNewRoute
  '/fertilizer/new': typeof FertilizerNewRoute
  '/soil-tests/new': typeof SoilTestsNewRoute
  '/yield/new': typeof YieldNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crop-cycles/new': typeof CropCyclesNewRoute
  '/farmers/new': typeof FarmersNewRoute
  '/farms/new': typeof FarmsNewRoute
  '/fertilizer/new': typeof FertilizerNewRoute
  '/soil-tests/new': typeof SoilTestsNewRoute
  '/yield/new': typeof YieldNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crop-cycles/new': typeof CropCyclesNewRoute
  '/farmers/new': typeof FarmersNewRoute
  '/farms/new': typeof FarmsNewRoute
  '/fertilizer/new': typeof FertilizerNewRoute
  '/soil-tests/new': typeof SoilTestsNewRoute
  '/yield/new': typeof YieldNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crop-cycles/new'
    | '/farmers/new'
    | '/farms/new'
    | '/fertilizer/new'
    | '/soil-tests/new'
    | '/yield/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crop-cycles/new'
    | '/farmers/new'
    | '/farms/new'
    | '/fertilizer/new'
    | '/soil-tests/new'
    | '/yield/new'
  id:
    | '__root__'
    | '/'
    | '/crop-cycles/new'
    | '/farmers/new'
    | '/farms/new'
    | '/fertilizer/new'
    | '/soil-tests/new'
    | '/yield/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CropCyclesNewRoute: typeof CropCyclesNewRoute
  FarmersNewRoute: typeof FarmersNewRoute
  FarmsNewRoute: typeof FarmsNewRoute
  FertilizerNewRoute: typeof FertilizerNewRoute
  SoilTestsNewRoute: typeof SoilTestsNewRoute
  YieldNewRoute: typeof YieldNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yield/new': {
      id: '/yield/new'
      path: '/yield/new'
      fullPath: '/yield/new'
      preLoaderRoute: typeof YieldNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil-tests/new': {
      id: '/soil-tests/new'
      path: '/soil-tests/new'
      fullPath: '/soil-tests/new'
      preLoaderRoute: typeof SoilTestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertilizer/new': {
      id: '/fertilizer/new'
      path: '/fertilizer/new'
      fullPath: '/fertilizer/new'
      preLoaderRoute: typeof FertilizerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/new': {
      id: '/farms/new'
      path: '/farms/new'
      fullPath: '/farms/new'
      preLoaderRoute: typeof FarmsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/new': {
      id: '/farmers/new'
      path: '/farmers/new'
      fullPath: '/farmers/new'
      preLoaderRoute: typeof FarmersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-cycles/new': {
      id: '/crop-cycles/new'
      path: '/crop-cycles/new'
      fullPath: '/crop-cycles/new'
      preLoaderRoute: typeof CropCyclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CropCyclesNewRoute: CropCyclesNewRoute,
  FarmersNewRoute: FarmersNewRoute,
  FarmsNewRoute: FarmsNewRoute,
  FertilizerNewRoute: FertilizerNewRoute,
  SoilTestsNewRoute: SoilTestsNewRoute,
  YieldNewRoute: YieldNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
